name: 'github'
version: '0.1.0'
require-dbt-version: ['>=1.0.0']
config-version: 2
profile: 'default'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  github:
    materialized: table
    intermediate:
      materialized: ephemeral

vars:
  github:
    pull_requests: "github_lowlighter_demo.pull_requests"
    issues_pull_request: "github_lowlighter_demo.issues_pull_request"
    issues: 'github_lowlighter_demo.issues'
    issues_user: 'github_lowlighter_demo.issues_user'
    labels: 'github_lowlighter_demo.issues_labels'
    issue_assignees: 'github_lowlighter_demo.issues_assignees'
    pull_request_stats: 'github_lowlighter_demo.pull_request_stats'
    reviews: 'github_lowlighter_demo.reviews'
    commits: 'github_lowlighter_demo.commits'
    commits_author: 'github_lowlighter_demo.commits_author'
    commits_committer: 'github_lowlighter_demo.commits_committer'
    commits_commit: 'github_lowlighter_demo.commits_commit'
    commit_comments_user: 'github_lowlighter_demo.commit_comments_user'
    commit_comment_reactions_user: 'github_lowlighter_demo.commit_comment_reactions_user'
    issue_comment_reactions_user: 'github_lowlighter_demo.issue_comment_reactions_user'
    issue_events_issue_user: 'github_lowlighter_demo.issue_events_issue_user'
    issue_reactions_user: 'github_lowlighter_demo.issue_reactions_user'
    pull_request_comment_reactions_user: 'github_lowlighter_demo.pull_request_comment_reactions_user'
    pull_request_commits: "github_lowlighter_demo.pull_request_commits"
    pull_requests_user: 'github_lowlighter_demo.pull_requests_user'
    review_comments_user: 'github_lowlighter_demo.review_comments_user'
    reviews_user: 'github_lowlighter_demo.reviews_user'
    stargazers_user: 'github_lowlighter_demo.stargazers_user'