name: 'airbyte_github'
version: '0.1.0'
require-dbt-version: ['>=1.0.0']
config-version: 2
profile: 'default'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  airbyte_github:
    materialized: table
    intermediate:
      materialized: ephemeral

vars:
  airbyte_github:
    pull_requests: "{{ source('airbyte_github','pull_requests') }}"
    issues_pull_request: "{{ source('airbyte_github','issues_pull_request') }}"
    issues: "{{ source('airbyte_github','issues') }}"
    issues_user: "{{ source('airbyte_github','issues_user') }}"
    labels: "{{ source('airbyte_github','issues_labels') }}"
    issue_assignees: "{{ source('airbyte_github','issues_assignees') }}"
    pull_request_stats: "{{ source('airbyte_github','pull_request_stats') }}"
    reviews: "{{ source('airbyte_github','reviews') }}"
    commits: "{{ source('airbyte_github','commits') }}"
    commits_author: "{{ source('airbyte_github','commits_author') }}"
    commits_committer: "{{ source('airbyte_github','commits_committer') }}"
    commits_commit: "{{ source('airbyte_github','commits_commit') }}"
    commit_comments_user: "{{ source('airbyte_github','commit_comments_user') }}"
    commit_comment_reactions_user: "{{ source('airbyte_github','commit_comment_reactions_user') }}"
    issue_comment_reactions_user: "{{ source('airbyte_github','issue_comment_reactions_user') }}"
    issue_events_issue_user: "{{ source('airbyte_github','issue_events_issue_user') }}"
    issue_reactions_user: "{{ source('airbyte_github','issue_reactions_user') }}"
    pull_request_comment_reactions_user: "{{ source('airbyte_github','pull_request_comment_reactions_user') }}"
    pull_request_commits: "{{ source('airbyte_github','pull_request_commits') }}"
    pull_requests_user: "{{ source('airbyte_github','pull_requests_user') }}"
    review_comments_user: "{{ source('airbyte_github','review_comments_user') }}"
    reviews_user: "{{ source('airbyte_github','reviews_user') }}"
    stargazers: "{{ source('airbyte_github','stargazers') }}"
    stargazers_user: "{{ source('airbyte_github','stargazers_user') }}"
