
version: 2

sources:
  - name: github
    schema: "{{ var('github_schema', 'github') }}"
    database: "{% if target.type != 'spark'%}{{ var('github_database', target.database) }}{% endif %}"
    tables:
      - name: pull_requests
      - name: issues_pull_request
      - name: issues
      - name: issues_user
      - name: labels
      - name: issue_assignees
      - name: pull_request_stats
      - name: reviews
      - name: commits
      - name: commits_author
      - name: commits_committer
      - name: commits_commit
      - name: commit_comments_user
      - name: commit_comment_reactions_user
      - name: issue_comment_reactions_user
      - name: issue_events_issue_user
      - name: issue_reactions_user
      - name: pull_request_comment_reactions_user
      - name: pull_request_commits
      - name: pull_requests_user
      - name: review_comments_user
      - name: reviews_user
      - name: stargazers
      - name: stargazers_user
      - name: issues_assignees
      - name: issues_labels

models:
  - name: github__pull_requests
    description: "A table storing all pull request information of your repositories in GitHub. Use this to extract information regarding pull requests."
    columns:
      - name: issue_id
        description: "The unique identifier for the issue being resolved"
        tests:
          - unique
          - not_null
      - name: author_user_id
        description: "The unique identifier for the user who created the pull request"
        tests:
          - not_null
      - name: author_username
        description: "The name of the user who created the pull request"
        tests:
          - not_null
      - name: issue_number
        description: "The number of the pull request"
        tests:
          - unique
          - not_null
      - name: state
        description: "The state of the pull request. Closed or open"
        tests:
          - not_null
      - name: title
        description: "The title of the pull request"
        tests:
          - not_null
      - name: repository_name
        description: "The name of the repository"
        tests:
          - not_null
      - name: link_url
        description: "The url of the pull request"
        tests:
          - unique
          - not_null
      - name: commits
        description: "The number of commits in the pull request"
        tests:
          - not_null
      - name: comments
        description: "The number of comments on the pull request"
        tests:
          - not_null
      - name: reviewers_count
        description: "The number of reviewers on the pull request"
      - name: days_issue_open
        description: "The number of dats the issue is open after being open"
      - name: days_until_first_review
        description: "The number of days until the first review since the pull request was created"
        tests:
      - name: closed_at_timestamp
        description: "The timestamp the pull request was closed"
      - name: created_at_timestamp
        description: "The timestamp the pull request was created"
        tests:
          - not_null
      - name: updated_at_timestamp
        description: "The timestamp the pull request was updated"
        tests:
          - not_null
  - name: github__commits
    description: "A table storing all commit information of your repositories in GitHub. Use this to extract information about commits in your repositories."
    columns:
      - name: sha
        description: "The unique hash for the commit"
        tests:
          - unique
          - not_null
      - name: repository_name
        description: "The name of the repository this commit was committed to"
        tests:
          - not_null
      - name: pull_request_id
        description: "The id of the pull request this commit is apart of"
      - name: pull_request_number
        description: "The number of the pull request this commit is apart of"
      - name: author_id
        description: "The unique identifier for the author of the commit"
        tests:
          - not_null
      - name: author_type
        description: "The type of user of the commit author"
        tests:
          - not_null
      - name: author_username
        description: "The username of the commit author"
        tests:
          - not_null
      - name: committer_type
        description: "The type of user of the commit committer"
        tests:
          - not_null
      - name: committer_username
        description: "The username of the commit committer"
        tests:
          - not_null
      - name: comment_count
        description: "The number of comments on the commit"
        tests:
          - not_null
      - name: message
        description: "The message attached to the commit"
        tests:
          - not_null
      - name: created_at
        description: "The timestamp the commit was created"
        tests:
          - not_null
  - name: github__issues
    description: "A table storing all issue information of your repositories in GitHub. Use this to extract information regarding issues."
    columns:
      - name: issue_id
        description: "The unique identifier for the issue being resolved"
        tests:
          - unique
          - not_null
      - name: state
        description: "The state of the issue. Closed or open"
        tests:
          - not_null
      - name: title
        description: "The title of the issue"
        tests:
          - not_null
      - name: issue_number
        description: "The number of the issue"
        tests:
          - unique
          - not_null
      - name: author_username
        description: "The username of the user who raised the issue"
        tests:
          - not_null
      - name: author_association
        description: "The association of the user. If they are a user, contributor etc"
        tests:
          - not_null
      - name: assignee_username
        description: "The username of the person who is assigned to the issue"
        tests:
      - name: comments
        description: "The number of comments that have appeared on the issue"
        tests:
          - not_null
      - name: days_issue_open
        description: "The number of days the issue has been open"
        tests:
      - name: created_at_timestamp
        description: "The timestamp the issue was created"
        tests:
          - not_null
      - name: updated_at_timestamp
        description: "The timestamp the issue was updated"
        tests:
          - not_null
      - name: closed_at_timestamp
        description: "The timestamp the issue was closed"
        tests:
  - name: github__users
    description: "A table storing all information regarding users in Github that have interacted with your repository"
    columns:
      - name: user_id
        description: "The unique identifier for the user"
        tests:
          - unique
          - not_null
      - name: url
        description: "The url of the users pull_request"
        tests:
          - unique
          - not_null
      - name: type
        description: "The type of user"
        tests:
          - not_null
      - name: username
        description: "The username of the user"
        tests:
          - not_null
  - name: github__stargazers
    description: "A table storing all information regarding repository stars by users"
    columns:
      - name: starred_at
        description: "The timestamp the repository was starred"
        tests:
          - not_null
      - name: user_id
        description: "The unique identifier for the user"
        tests:
          - unique
          - not_null
      - name: user_type
        description: "The type of the user"
        tests:
          - not_null
      - name: username
        description: "The username of the user"
        tests:
          - not_null
      - name: is_site_admin
        description: "A flag for whether the user was an admin of the organization"
        tests:
          - not_null



metrics:
  - name: number_of_pull_requests
    label: Number of pull requests
    model: ref('github__pull_requests')
    description: "The number of pull requests"

    type: count
    sql: issue_id

    timestamp: created_at_timestamp
    time_grains: [day, week, month]

    dimensions:
      - state

  - name: average_commits_per_pull_request
    label: Average number of commits per pull request
    model: ref('github__pull_requests')
    description: "The average number of commits per pull request"

    type: average
    sql: commits

    timestamp: created_at_timestamp
    time_grains: [day, week, month]

  - name: average_comments_per_pull_request
    label: Average number of comments per pull request
    model: ref('github__pull_requests')
    description: "The average number of comments per pull request"

    type: average
    sql: comments

    timestamp: created_at_timestamp
    time_grains: [day, week, month]

  - name: average_days_open_per_pull_request
    label: Average number of open days per pull request
    model: ref('github__pull_requests')
    description: "The average number of days pull requests remain open"

    type: average
    sql: days_issue_open

    timestamp: created_at_timestamp
    time_grains: [day, week, month]

  - name: average_days_until_first_review
    label: Average number of days until first review
    model: ref('github__pull_requests')
    description: "The average number of days until the first review on a pull request"

    type: average
    sql: days_until_first_review

    timestamp: created_at_timestamp
    time_grains: [day, week, month]

  - name: number_of_issues
    label: The number of issues
    model: ref('github__issues')
    description: "The number of issues in the repository"

    type: count
    sql: issue_id

    timestamp: created_at_timestamp
    time_grains: [day, week, month]

    dimensions:
      - state
      - author_association

  - name: average_number_of_comments
    label: The average number of comments
    model: ref('github__issues')
    description: "The average number of comments in each repository"

    type: average
    sql: comments

    timestamp: created_at_timestamp
    time_grains: [day, week, month]

  - name: average_number_of_days_issue_open
    label: The average number of days issue open
    model: ref('github__issues')
    description: "The average number of days issues remain open"

    type: average
    sql: days_issue_open

    timestamp: created_at_timestamp
    time_grains: [day, week, month]

